name: AutoRelease
on:
  push:
    branches: [master]
jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.2
      - run: |
          mkdir -p /home/runner/go/src/github.com/sshh12
          ln -s /home/runner/work/venmo-research/venmo-research /home/runner/go/src/github.com/sshh12/venmo-research
          go get github.com/open-telemetry/opentelemetry-go
          mkdir -p /home/runner/go/src/go.opentelemetry.io
          ln -s /home/runner/go/src/github.com/go.opentelemetry.io/otel /home/runner/go/src/go.opentelemetry.io/otel
          go get -v github.com/go-pg/pg
      - run: GOOS=${{ matrix.goos }} go build -o scrape-venmo -v ./cmd/scrape 
