name: AutoRelease
on:
  push:
    branches: [master]
jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
        project_path: ["./cmd/scrape"]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ${{ matrix.project_path }}
          pre_command: "go get -v go.opentelemetry.io/otel/api/trace github.com/go-pg/pg github.com/sshh12/venmo-research/storage github.com/sshh12/venmo-research/venmo"
          extra_files: LICENSE README.md
