name: AutoRelease
on:
  push:
    branches: [master]
jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.2
      - run: ls
      - run: pwd
      - run: go build -o scrape-venmo -v ./cmd/scrape 
      - run: ls
